###########
# site.title, site.url, site.author.name

title:   'Blog Posts By Alex-Esc'
author: 
  name:  'Blog Posts'
description:  I write about art & tech.

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: '/posts'
url:  'https://alex-esc.github.io'
baseurl: '/posts'


########
# more settings





markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

plugins:
  - jekyll-redirect-from



excerpt_separator: <!--more-->

kramdown:
  auto_ids: true # Auto-generate ID's for headings