###########
# site.title, site.url, site.author.name

title:   'hyphen esc'
author: 
  name:  'hyphen esc'
description:  hyphen esc.

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: 'https://hyphenesc.github.io/' #'/posts'
url:  'https://hyphenesc.github.io/'
baseurl: '' #'/posts'

other:
  music: 'https://hyphenesc.github.io/music'
  video: 'https://hyphenesc.github.io/video'
  about: 'https://hyphenesc.github.io/about'
  posts: 'https://hyphenesc.github.io/posts'

########
# more settings





markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

plugins:
  - jekyll-redirect-from



excerpt_separator: <!--more-->

kramdown:
  auto_ids: true # Auto-generate ID's for headings